exception_logger/__init__.py,sha256=47DEQpj8HBSa-_TImW-5JCeuQeRkm5NMpJWZG3hSuFU,0
exception_logger/apps.py,sha256=3UdUD7uAMWlA42xDi7iufnlbxn6RNBeigVAbC8BrGTQ,253
exception_logger/forms.py,sha256=RbEwBHXaKRX3U-psstFID3DvmExXjZwO19M1TxyOp0g,391
exception_logger/signals.py,sha256=sdggT0kSZc57ab1z2P5uoK0BIsIa5Ya2t7GIhZlKtKc,1457
exception_logger/utils.py,sha256=M30otVAH00LUu28nIc4itHec2NCexw85lbjE5ZZbWJk,388
django_exception_logger-0.0.1.dist-info/LICENSE,sha256=HjPmtEqQVLR-jMti-IMo1YrqOF_NTWjNxZzegNwcVlc,1065
django_exception_logger-0.0.1.dist-info/METADATA,sha256=V5mU62lGCNrn-9K1He0QEP5MgbVreWkPmeyndJqBdxs,1709
django_exception_logger-0.0.1.dist-info/WHEEL,sha256=G16H4A3IeoQmnOrYV4ueZGKSjhipXx8zc8nu9FGlvMA,92
django_exception_logger-0.0.1.dist-info/top_level.txt,sha256=3OZXBFxvVMBjQpvg6T2Hxt4oviBkizfV6XBADM9wX14,17
django_exception_logger-0.0.1.dist-info/RECORD,,
